version: 2

sources:
  - name: jaffle_shop
    description: A clone of a Postgres application database.
    database: dbt
    schema: dev_data
    tables:
      - name: customers
        description: Raw customers data.
        loaded_at_field: loaded_at_field
        warn_after: {count: 2, period: minute}
        error_after: {count: 4, period: minute}
        columns:
          - name: id
            description: Primary key for customers.
      - name: payments
        description: Raw payments data.
      - name: orders
        description: Raw orders data.